# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mg0LAOvg8Tj_yGMqfqlMzm0qY1GCaTeV
"""

# Install the core stack
!pip install -q langchain langchain-openai langchain-core langgraph
!pip install -q fastmcp chromadb gradio python-dotenv

import os
import chromadb
from google.colab import userdata

# Set your OpenRouter API Key (Create a secret in Colab named 'OPENROUTER_API_KEY')
try:
    os.environ["OPENROUTER_API_KEY"] = userdata.get('OPENROUTER_API_KEY')
except Exception:
    # Fallback for manual entry if Colab secrets aren't set
    os.environ["OPENROUTER_API_KEY"] = "YOUR_API_KEY"

# Initialize ChromaDB for Agent Memory
print("Initializing ChromaDB Memory...")
chroma_client = chromadb.Client()

# Create a collection for our knowledge base
try:
    kb_collection = chroma_client.create_collection(name="enterprise_knowledge")

    # Inject enterprise documents (OSHA rules, inventory protocols, etc.)
    kb_collection.add(
        documents=[
            "OSHA Standard 1910.135: All factory workers must wear protective hard hats in active machine zones.",
            "OSHA Standard 1910.133: Safety goggles are required when operating welding equipment.",
            "Inventory Protocol A-12: Any visibly damaged products on the retail shelf must be flagged in the SQL database as 'DAMAGED_PENDING_REVIEW'."
        ],
        ids=["doc1", "doc2", "doc3"],
        metadatas=[{"source": "osha"}, {"source": "osha"}, {"source": "internal_policy"}]
    )
    print("Memory populated with enterprise documents.")
except Exception as e:
    print("Collection already exists or error:", e)

from fastmcp import FastMCP
from langchain_core.tools import tool

# Initialize the FastMCP Server
mcp = FastMCP("Vision-Agent-Tools")

# 1. Memory Retrieval Tool
@mcp.tool
def search_knowledge_base(query: str) -> str:
    """
    Search the enterprise knowledge base, OSHA regulations, and company policies.
    Use this tool whenever you need to check rules, guidelines, or protocols.
    """
    results = kb_collection.query(query_texts=[query], n_results=1)
    if results['documents'] and results['documents'][0]:
        return f"Found document: {results['documents'][0][0]}"
    return "No relevant guidelines found."

# 2. Mock SQL Database Tool
@mcp.tool
def query_inventory_db(product_name: str) -> str:
    """
    Query the enterprise SQL database to get current inventory levels and status for a product.
    """
    # In reality, this would connect to PostgreSQL/MySQL
    return f"[Database Response] {product_name}: 14 units in stock. Last inspected: 2 days ago."

# Convert FastMCP tools to LangChain compatible tools for the orchestrator
# Note: In a decoupled system, LangChain's MCP adapters would handle this via network calls.
agent_tools = [
    tool(search_knowledge_base),
    tool(query_inventory_db)
]

print(f"Registered MCP Tools: {[t.name for t in agent_tools]}")

from langchain_openai import ChatOpenAI
from langgraph.prebuilt import create_react_agent
from langchain_core.messages import HumanMessage

# Initialize Vision-Language Model via OpenRouter
# We use Alibaba's highly capable Qwen2.5-VL model
llm = ChatOpenAI(
    model="openrouter/free",
    api_key=os.environ.get("OPENROUTER_API_KEY"),
    base_url="https://openrouter.ai/api/v1",
    temperature=0.2, # Low temperature for analytical reasoning
)

# Create the Agentic Loop using LangGraph
# This handles: Image -> Reason -> Call Tool -> Observe -> Reason -> Answer
vision_agent = create_react_agent(llm, agent_tools)

print("Agentic Orchestrator Ready.")

import base64
import gradio as gr

def encode_image_to_base64(image_filepath):
    """Convert local Gradio image to base64 for the API."""
    with open(image_filepath, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode("utf-8")

def process_visual_query(image_filepath, text_query):
    if not image_filepath:
        return "Please upload an image.", "Error: No image provided."

    if not os.environ.get("OPENROUTER_API_KEY") or os.environ.get("OPENROUTER_API_KEY") == "sk-or-your-api-key-here":
        return "API Key Missing", "Please set your OPENROUTER_API_KEY in Cell 2."

    # 1. Encode Image
    b64_image = encode_image_to_base64(image_filepath)

    # 2. Format multimodal message for LangChain / OpenRouter
    message = HumanMessage(
        content=[
            {"type": "text", "text": text_query},
            {
                "type": "image_url",
                "image_url": {"url": f"data:image/jpeg;base64,{b64_image}"}
            }
        ]
    )

    # 3. Execute Agent Loop and capture internal thoughts
    thought_log = []
    final_answer = ""

    try:
        # Stream the graph execution steps
        for step in vision_agent.stream({"messages": [message]}):
            for key, value in step.items():
                if key == "agent":
                    # The agent is thinking or deciding to call a tool
                    agent_message = value["messages"][-1]
                    if agent_message.tool_calls:
                        for tool_call in agent_message.tool_calls:
                            thought_log.append(f"🛠️ **Agent deciding to use tool:** `{tool_call['name']}`\n   *Arguments:* {tool_call['args']}")
                    else:
                        final_answer = agent_message.content

                elif key == "tools":
                    # The tool has returned an observation
                    tool_message = value["messages"][-1]
                    thought_log.append(f"🔍 **Tool Observation:** {tool_message.content}")

    except Exception as e:
        return f"Execution Error: {str(e)}", "Agent failed to complete the task."

    # Format the thought process for the UI
    formatted_thoughts = "\n\n".join(thought_log) if thought_log else "No external tools were needed for this query."

    return formatted_thoughts, final_answer

# Build the Gradio Interface
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 👁️ Agentic Vision System (MCP + LangGraph + Qwen2.5-VL)")
    gr.Markdown("Upload an image and ask a complex question requiring external knowledge (e.g., 'Are these workers following OSHA safety rules?' or 'Check inventory for the damaged items on this shelf').")

    with gr.Row():
        with gr.Column(scale=1):
            image_input = gr.Image(type="filepath", label="Upload Scene")
            text_input = gr.Textbox(label="Agent Prompt", placeholder="What do you want the agent to analyze?")
            submit_btn = gr.Button("Run Agentic Analysis", variant="primary")

        with gr.Column(scale=1):
            with gr.Accordion("Agent Reasoning Log (Think -> Act -> Observe)", open=True):
                reasoning_output = gr.Markdown("Waiting for execution...")
            final_output = gr.Textbox(label="Final Agent Report", lines=8)

    submit_btn.click(
        fn=process_visual_query,
        inputs=[image_input, text_input],
        outputs=[reasoning_output, final_output]
    )

# Launch the app in the Colab cell output
demo.launch(debug=True, share=True)

